import { Router } from 'express';
import authRoutes from './auth.routes';
import institutionRoutes from './institution.routes';
import superAdminRoutes from './superadmin.routes';
import facultyRoutes from './faculties.routes';
import departmentRoutes from './departments.routes';
import studentRoutes from './students.routes';
import sessionRoutes from './sessions.routes';
import courseRoutes from './courses.routes';
import resultRoutes from './results.routes';
import documentRoutes from './documents.routes';
import verifyRoutes from './verify.routes';
import auditRoutes from './audit.routes';
import adminRoutes from './admin.routes';

export const router = Router();

router.use('/auth', authRoutes);
router.use('/institution', institutionRoutes);
router.use('/faculties', facultyRoutes);
router.use('/departments', departmentRoutes);
router.use('/students', studentRoutes);
router.use('/sessions', sessionRoutes);
router.use('/courses', courseRoutes);
router.use('/results', resultRoutes);
router.use('/documents', documentRoutes);
router.use('/verify', verifyRoutes);
router.use('/audit', auditRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/admin', adminRoutes);
router.use('/super-admin', superAdminRoutes);
