/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VerifyTamperedRouteImport } from './routes/verify.tampered'
import { Route as VerifyResultRouteImport } from './routes/verify.result'
import { Route as VerifyNotFoundRouteImport } from './routes/verify.not-found'
import { Route as StudentShareRouteImport } from './routes/student.share'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentDocumentsRouteImport } from './routes/student.documents'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminStudentsMatricRouteImport } from './routes/admin.students.$matric'
import { Route as AdminResultsNewRouteImport } from './routes/admin.results.new'
import { Route as AdminDocumentsUploadRouteImport } from './routes/admin.documents.upload'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyTamperedRoute = VerifyTamperedRouteImport.update({
  id: '/verify/tampered',
  path: '/verify/tampered',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyResultRoute = VerifyResultRouteImport.update({
  id: '/verify/result',
  path: '/verify/result',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyNotFoundRoute = VerifyNotFoundRouteImport.update({
  id: '/verify/not-found',
  path: '/verify/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentShareRoute = StudentShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDocumentsRoute = StudentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StudentRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsMatricRoute = AdminStudentsMatricRouteImport.update({
  id: '/$matric',
  path: '/$matric',
  getParentRoute: () => AdminStudentsRoute,
} as any)
const AdminResultsNewRoute = AdminResultsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminResultsRoute,
} as any)
const AdminDocumentsUploadRoute = AdminDocumentsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminDocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/results': typeof AdminResultsRouteWithChildren
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/student/documents': typeof StudentDocumentsRoute
  '/student/results': typeof StudentResultsRoute
  '/student/share': typeof StudentShareRoute
  '/verify/not-found': typeof VerifyNotFoundRoute
  '/verify/result': typeof VerifyResultRoute
  '/verify/tampered': typeof VerifyTamperedRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/documents/upload': typeof AdminDocumentsUploadRoute
  '/admin/results/new': typeof AdminResultsNewRoute
  '/admin/students/$matric': typeof AdminStudentsMatricRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/results': typeof AdminResultsRouteWithChildren
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/student/documents': typeof StudentDocumentsRoute
  '/student/results': typeof StudentResultsRoute
  '/student/share': typeof StudentShareRoute
  '/verify/not-found': typeof VerifyNotFoundRoute
  '/verify/result': typeof VerifyResultRoute
  '/verify/tampered': typeof VerifyTamperedRoute
  '/admin': typeof AdminIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/documents/upload': typeof AdminDocumentsUploadRoute
  '/admin/results/new': typeof AdminResultsNewRoute
  '/admin/students/$matric': typeof AdminStudentsMatricRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/results': typeof AdminResultsRouteWithChildren
  '/admin/students': typeof AdminStudentsRouteWithChildren
  '/student/documents': typeof StudentDocumentsRoute
  '/student/results': typeof StudentResultsRoute
  '/student/share': typeof StudentShareRoute
  '/verify/not-found': typeof VerifyNotFoundRoute
  '/verify/result': typeof VerifyResultRoute
  '/verify/tampered': typeof VerifyTamperedRoute
  '/admin/': typeof AdminIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/documents/upload': typeof AdminDocumentsUploadRoute
  '/admin/results/new': typeof AdminResultsNewRoute
  '/admin/students/$matric': typeof AdminStudentsMatricRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/documents'
    | '/admin/results'
    | '/admin/students'
    | '/student/documents'
    | '/student/results'
    | '/student/share'
    | '/verify/not-found'
    | '/verify/result'
    | '/verify/tampered'
    | '/admin/'
    | '/student/'
    | '/admin/documents/upload'
    | '/admin/results/new'
    | '/admin/students/$matric'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/documents'
    | '/admin/results'
    | '/admin/students'
    | '/student/documents'
    | '/student/results'
    | '/student/share'
    | '/verify/not-found'
    | '/verify/result'
    | '/verify/tampered'
    | '/admin'
    | '/student'
    | '/admin/documents/upload'
    | '/admin/results/new'
    | '/admin/students/$matric'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/admin/audit'
    | '/admin/departments'
    | '/admin/documents'
    | '/admin/results'
    | '/admin/students'
    | '/student/documents'
    | '/student/results'
    | '/student/share'
    | '/verify/not-found'
    | '/verify/result'
    | '/verify/tampered'
    | '/admin/'
    | '/student/'
    | '/admin/documents/upload'
    | '/admin/results/new'
    | '/admin/students/$matric'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  VerifyNotFoundRoute: typeof VerifyNotFoundRoute
  VerifyResultRoute: typeof VerifyResultRoute
  VerifyTamperedRoute: typeof VerifyTamperedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/tampered': {
      id: '/verify/tampered'
      path: '/verify/tampered'
      fullPath: '/verify/tampered'
      preLoaderRoute: typeof VerifyTamperedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/result': {
      id: '/verify/result'
      path: '/verify/result'
      fullPath: '/verify/result'
      preLoaderRoute: typeof VerifyResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/not-found': {
      id: '/verify/not-found'
      path: '/verify/not-found'
      fullPath: '/verify/not-found'
      preLoaderRoute: typeof VerifyNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/share': {
      id: '/student/share'
      path: '/share'
      fullPath: '/student/share'
      preLoaderRoute: typeof StudentShareRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/documents': {
      id: '/student/documents'
      path: '/documents'
      fullPath: '/student/documents'
      preLoaderRoute: typeof StudentDocumentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$matric': {
      id: '/admin/students/$matric'
      path: '/$matric'
      fullPath: '/admin/students/$matric'
      preLoaderRoute: typeof AdminStudentsMatricRouteImport
      parentRoute: typeof AdminStudentsRoute
    }
    '/admin/results/new': {
      id: '/admin/results/new'
      path: '/new'
      fullPath: '/admin/results/new'
      preLoaderRoute: typeof AdminResultsNewRouteImport
      parentRoute: typeof AdminResultsRoute
    }
    '/admin/documents/upload': {
      id: '/admin/documents/upload'
      path: '/upload'
      fullPath: '/admin/documents/upload'
      preLoaderRoute: typeof AdminDocumentsUploadRouteImport
      parentRoute: typeof AdminDocumentsRoute
    }
  }
}

interface AdminDocumentsRouteChildren {
  AdminDocumentsUploadRoute: typeof AdminDocumentsUploadRoute
}

const AdminDocumentsRouteChildren: AdminDocumentsRouteChildren = {
  AdminDocumentsUploadRoute: AdminDocumentsUploadRoute,
}

const AdminDocumentsRouteWithChildren = AdminDocumentsRoute._addFileChildren(
  AdminDocumentsRouteChildren,
)

interface AdminResultsRouteChildren {
  AdminResultsNewRoute: typeof AdminResultsNewRoute
}

const AdminResultsRouteChildren: AdminResultsRouteChildren = {
  AdminResultsNewRoute: AdminResultsNewRoute,
}

const AdminResultsRouteWithChildren = AdminResultsRoute._addFileChildren(
  AdminResultsRouteChildren,
)

interface AdminStudentsRouteChildren {
  AdminStudentsMatricRoute: typeof AdminStudentsMatricRoute
}

const AdminStudentsRouteChildren: AdminStudentsRouteChildren = {
  AdminStudentsMatricRoute: AdminStudentsMatricRoute,
}

const AdminStudentsRouteWithChildren = AdminStudentsRoute._addFileChildren(
  AdminStudentsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDocumentsRoute: typeof AdminDocumentsRouteWithChildren
  AdminResultsRoute: typeof AdminResultsRouteWithChildren
  AdminStudentsRoute: typeof AdminStudentsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDocumentsRoute: AdminDocumentsRouteWithChildren,
  AdminResultsRoute: AdminResultsRouteWithChildren,
  AdminStudentsRoute: AdminStudentsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentDocumentsRoute: typeof StudentDocumentsRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentShareRoute: typeof StudentShareRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDocumentsRoute: StudentDocumentsRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentShareRoute: StudentShareRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  VerifyNotFoundRoute: VerifyNotFoundRoute,
  VerifyResultRoute: VerifyResultRoute,
  VerifyTamperedRoute: VerifyTamperedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
